apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: bm25-pipeline-
  namespace: argo
spec:
  entrypoint: pipeline

  templates:

  # ------------------------------------------------
  # PIPELINE DAG
  # ------------------------------------------------
  - name: pipeline
    steps:
      - - name: generate-features
          template: generate-features

      - - name: feast-materialize
          template: feast-materialize

      - - name: ridge-normalize
          template: ridge-normalize
  # ------------------------------------------------
  # STEP 1 — FEATURE GENERATION
  # ------------------------------------------------
  - name: generate-features
    container:
      image: bm25-pipeline:local
      imagePullPolicy: IfNotPresent
      command: ["python"]
      args: ["src/generate_features_wide.py"]

      volumeMounts:
        - name: data
          mountPath: /mnt/data
  # ------------------------------------------------
  # STEP 2 — FEAST MATERIALIZE
  # ------------------------------------------------
  - name: feast-materialize
    container:
      image: bm25-pipeline:local
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh","-c"]
      args:
        - |
          cd feature_repo
          pwd
          feast materialize-incremental $(date -u +"%Y-%m-%dT%H:%M:%S")

      volumeMounts:
        - name: data
          mountPath: /mnt/data
  # ------------------------------------------------
  # STEP 3 — MODEL TRAINING
  # ------------------------------------------------
  - name: ridge-normalize
    container:
      image: bm25-pipeline:local
      imagePullPolicy: IfNotPresent
      command: ["python"]
      args: ["src/ridge_normalize.py"]

      volumeMounts:
        - name: data
          mountPath: /mnt/data

  # ------------------------------------------------
  # SHARED VOLUME
  # ------------------------------------------------
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: pipeline-data