apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: bm25-ranking-pipeline-
  namespace: argo
spec:
  entrypoint: ranking-dag
  imagePullSecrets:
    - name: github-creds
  volumes:
  - name: pipeline-storage
    persistentVolumeClaim:
      claimName: argo-pvc

  templates:
  - name: ranking-dag
    dag:
      tasks:
        # STEP 1: Bootstrap and Registry Apply
        - name: feast-apply
          template: run-python-step
          arguments:
            parameters:
              - name: script
                value: |
                  import os
                  from src import generate_features_wide as gen
                  repo_path = os.getenv("FEAST_REPO_PATH")
                  gen.bootstrap_feast_repo(repo_path)
                  os.chdir(repo_path)
                  if os.system("feast apply") != 0:
                      raise RuntimeError("Feast apply failed")

        # STEP 2: Ingest local data (NOW USES A TEMPLATE)
        - name: ingest-to-feast
          dependencies: [feast-apply]
          template: ingest-template

        # STEP 3: Train the model using features from Feast
        - name: ridge-training
          dependencies: [ingest-to-feast]
          template: run-python-step
          arguments:
            parameters:
              - name: script
                value: |
                  from src import ridge_normalize as ridge
                  import yaml, os
                  
                  # Load paths from the container's config
                  with open('/app/configs/config.yaml') as f: 
                      config = yaml.safe_load(f)
                  
                  # Use the exact key from your config: config['data']['clicks_json']
                  # which resolves to '/app/data/person_search_clicks.json'
                  ridge.run(
                      repo_path=os.getenv("FEAST_REPO_PATH"),
                      clicks_json=config['data']['clicks_json'],
                      bm25_fields=config['features']['bm25_fields'],
                      alpha=config['ridge']['alpha'],
                      output_file='/mnt/data/bm25_field_weights.csv'
                  )

  # Template for simple python strings
  - name: run-python-step
    inputs:
      parameters:
        - name: script
    container:
      image: ghcr.io/dylanyops/solr-edismax-boost:latest
      imagePullPolicy: Always
      command: ["python", "-c"]
      args: ["{{inputs.parameters.script}}"]
      env:
        - name: FEAST_REPO_PATH
          value: "/mnt/data/feature_repo"
      volumeMounts:
        - name: pipeline-storage
          mountPath: /mnt/data

  # NEW: Dedicated template for ingestion to avoid YAML mapping errors
  - name: ingest-template
    container:
      image: ghcr.io/dylanyops/solr-edismax-boost:latest
      command: ["python3", "-c"]
      args: 
        - |
          from src.generate_features_wide import run
          run(
            repo_path='/mnt/data/feature_repo', 
            feature_source_path='/mnt/data/features.json'
          )
      volumeMounts:
        - name: pipeline-storage
          mountPath: /mnt/data