apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: bm25-ranking-pipeline-
  namespace: argo
spec:
  entrypoint: ranking-dag

  imagePullSecrets:
    - name: github-creds
  
  volumes:
  - name: pipeline-storage
    persistentVolumeClaim:
      claimName: argo-pvc

  templates:
  - name: ranking-dag
    dag:
      tasks:
        - name: generate-wide
          template: run-python-step
          arguments:
            parameters:
              - name: script
                value: |
                  from src import generate_features_wide as gen;
                  # Match these to your config.yaml & actual image structure
                  gen.run(debugqueries_json='/app/data/person_search_debugQueries.json', 
                          clicks_json='/app/data/person_search_clicks.json', 
                          output_file='/mnt/data/bm25_features_wide.csv')

        - name: feature-engineering
          dependencies: [generate-wide]
          template: run-python-step
          arguments:
            parameters:
              - name: script
                value: |
                  from src import feature_engineering as feat;
                  feat.run(features_file='/mnt/data/bm25_features_wide.csv', 
                           clicks_file='/app/data/person_search_clicks.json', 
                           bm25_fields=['bm25_first_name', 'bm25_last_name', 'bm25_institution'], 
                           output_file='/mnt/data/bm25_pairwise_deltas_normalized.csv')

        - name: ridge-training
          dependencies: [feature-engineering]
          template: run-python-step
          arguments:
            parameters:
              - name: script
                value: |
                  from src import ridge_normalize as ridge;
                  ridge.run(input_file='/mnt/data/bm25_pairwise_deltas_normalized.csv', 
                            alpha=1.0, 
                            output_file='/mnt/data/bm25_field_weights.csv')

  - name: run-python-step
    inputs:
      parameters:
        - name: script
    container:
      image: ghcr.io/dylanyops/solr-edismax-boost:latest
      imagePullPolicy: Always
      command: ["python", "-c"]
      args: ["{{inputs.parameters.script}}"]
      env:
        - name: MLFLOW_TRACKING_URI
          value: "http://host.docker.internal:5000"
      volumeMounts:
        - name: pipeline-storage
          mountPath: /mnt/data